name: Call by required workflow

on:
  push:
    paths:
      - .github/workflows/**
  pull_request:
    paths:
      - .github/workflows/**

jobs:
  analyze:
    name: Analyze 
    runs-on: 'ubuntu-latest'
    permissions:
      # required for all workflows
      security-events: write

    strategy:
      fail-fast: false
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare CodeQL CLI
      run: |
        wget https://github.com/github/codeql-cli-binaries/releases/download/v2.22.1/codeql-linux64.zip && 
        unzip codeql-linux64.zip
        sudo mv codeql /usr/local/codeql
        sudo ln -s /usr/local/codeql/codeql /usr/local/bin/codeql

    - name: Create codeql db
      run: codeql database create codeql-db --language=actions --source-root ./

    - name: Run codeql analysis
      run: codeql database analyze codeql-db --format=sarif-latest --output=/tmp/codeql-results.sarif
