name: Call by required workflow

on:
  push:
    paths:
      - .github/workflows/**
  pull_request:
    paths:
      - .github/workflows/**

jobs:
  analyze:
    name: Analyze 
    runs-on: 'ubuntu-latest'
    permissions:
      # required for all workflows
      security-events: write

    strategy:
      fail-fast: false
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare CodeQL CLI
      run: |
        curl -L -o codeql-bundle.tar.gz https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.22.1/codeql-bundle-linux64.tar.gz
        tar -xzf codeql-bundle.tar.gz
        ls -l codeql
        sudo mv codeql /usr/local/codeql
        sudo ln -s /usr/local/codeql/codeql /usr/local/bin/codeql
        codeql --version
        codeql resolve packs

    - name: Create codeql db
      run: codeql database create codeql-db --language=actions --source-root ./

    - name: Run codeql analysis
      run: codeql database analyze codeql-db --format=sarif-latest --output=/tmp/codeql-results.sarif
    
    - name: Upload SARIF results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: /tmp/codeql-results.sarif
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
