name: Call by required workflow

on:
  push:
    paths:
      - .github/workflows/**
  pull_request:
    paths:
      - .github/workflows/**

jobs:
  analyze:
    name: Analyze 
    runs-on: 'ubuntu-latest'
    permissions:
      # required for all workflows
      security-events: write

    strategy:
      fail-fast: false
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare CodeQL CLI
      run: |
        latest_version=$(curl -s https://api.github.com/repos/github/codeql-action/releases/latest | jq -r .tag_name)
        curl -L -o codeql-bundle.tar.gz https://github.com/github/codeql-action/releases/download/${latest_version}/codeql-bundle-linux64.tar.gzmkdir codeql-cli
        tar -xzf codeql-bundle.tar.gz -C codeql-cli --strip-components=1

        # Add CodeQL CLI to PATH for subsequent steps
        echo "${PWD}/codeql-cli" >> $GITHUB_PATH
        echo "CodeQL CLI set up at: ${PWD}/codeql-cli"
        codeql resolve packs

    - name: Create codeql db
      run: codeql database create codeql-db --language=actions --source-root ./

    - name: Run codeql analysis
      run: codeql database analyze codeql-db --format=sarif-latest --output=/tmp/codeql-results.sarif
